### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SgtChrisCross** [KazWolfe/CollectorsAnxiety#8]
![image](https://github.com/KazWolfe/CollectorsAnxiety/assets/53583350/e976cb83-847c-4e5e-bfbb-6fcc9346397e)
![image](https://github.com/KazWolfe/CollectorsAnxiety/assets/53583350/5673170a-6726-4f0e-9b1a-db181d8d65ed)

**Comment by KazWolfe** [comment]
Should be fixed as of v0.0.5 in c03458e0ce7db540e869ac10dd6cce083101f2fd.
